/**
 * Mistral AI model definitions
 * @module models/providers/mistral
 */

import type { ModelInfo } from "../types.js";

/**
 * Mistral AI model catalog
 * Pricing: https://mistral.ai/technology/#pricing
 * Models: https://docs.mistral.ai/getting-started/models/
 */
export const MISTRAL_MODELS: ModelInfo[] = [
  // ==========================================================================
  // Flagship Models (2025)
  // ==========================================================================
  {
    id: "mistral-large-3-25-12",
    name: "Mistral Large 3",
    provider: "mistral",
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 2.0,
    outputPrice: 6.0,
    deprecated: false,
    description: "Mistral Large 3 flagship model",
  },
  {
    id: "mistral-medium-3-1-25-08",
    name: "Mistral Medium 3.1",
    provider: "mistral",
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 1.0,
    outputPrice: 3.0,
    deprecated: false,
    description: "Mistral Medium 3.1 balanced model",
  },
  {
    id: "mistral-small-3-2-25-06",
    name: "Mistral Small 3.2",
    provider: "mistral",
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.1,
    outputPrice: 0.3,
    deprecated: false,
    description: "Mistral Small 3.2 efficient model",
  },
  // ==========================================================================
  // Code Models (Devstral Series)
  // ==========================================================================
  {
    id: "devstral-2-25-12",
    name: "Devstral 2",
    provider: "mistral",
    contextWindow: 262_144,
    maxOutputTokens: 16_384,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.5,
    outputPrice: 1.5,
    deprecated: false,
    description: "Frontier code agents model",
  },
  {
    id: "devstral-small-2-25-12",
    name: "Devstral Small 2",
    provider: "mistral",
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.2,
    outputPrice: 0.6,
    deprecated: false,
    description: "Compact code agents model",
  },
  {
    id: "codestral-25-08",
    name: "Codestral (Aug 2025)",
    provider: "mistral",
    contextWindow: 262_144,
    maxOutputTokens: 16_384,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.3,
    outputPrice: 0.9,
    deprecated: false,
    description: "Codestral August 2025 release",
  },
  // ==========================================================================
  // Reasoning Models (Magistral Series)
  // ==========================================================================
  {
    id: "magistral-medium-1-2-25-09",
    name: "Magistral Medium",
    provider: "mistral",
    contextWindow: 131_072,
    maxOutputTokens: 16_384,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 1.5,
    outputPrice: 4.5,
    deprecated: false,
    description: "Magistral reasoning model (medium)",
  },
  {
    id: "magistral-small-1-2-25-09",
    name: "Magistral Small",
    provider: "mistral",
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.5,
    outputPrice: 1.5,
    deprecated: false,
    description: "Magistral reasoning model (small)",
  },
  // ==========================================================================
  // Small Models (Ministral Series)
  // ==========================================================================
  {
    id: "ministral-3-14b-25-12",
    name: "Ministral 3 14B",
    provider: "mistral",
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.07,
    outputPrice: 0.21,
    deprecated: false,
    description: "Ministral 3 14B parameter model",
  },
  {
    id: "ministral-3-8b-25-12",
    name: "Ministral 3 8B",
    provider: "mistral",
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.05,
    outputPrice: 0.15,
    deprecated: false,
    description: "Ministral 3 8B parameter model",
  },
  {
    id: "ministral-3-3b-25-12",
    name: "Ministral 3 3B",
    provider: "mistral",
    contextWindow: 65_536,
    maxOutputTokens: 4_096,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.02,
    outputPrice: 0.06,
    deprecated: false,
    description: "Ministral 3 3B parameter model",
  },
  // ==========================================================================
  // Audio Models (Voxtral Series)
  // ==========================================================================
  {
    id: "voxtral-small-25-07",
    name: "Voxtral Small",
    provider: "mistral",
    contextWindow: 65_536,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.1,
    outputPrice: 0.3,
    deprecated: false,
    description: "Audio input model (small)",
  },
  {
    id: "voxtral-mini-25-07",
    name: "Voxtral Mini",
    provider: "mistral",
    contextWindow: 32_768,
    maxOutputTokens: 4_096,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.05,
    outputPrice: 0.15,
    deprecated: false,
    description: "Audio input model (mini)",
  },
  // ==========================================================================
  // Mistral Large Series (Premium)
  // ==========================================================================
  {
    id: "mistral-large-latest",
    name: "Mistral Large",
    provider: "mistral",
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 2.0,
    outputPrice: 6.0,
    deprecated: false,
    description: "Mistral's flagship model for complex tasks",
  },
  // ==========================================================================
  // Codestral (Coding)
  // ==========================================================================
  {
    id: "codestral-latest",
    name: "Codestral",
    provider: "mistral",
    contextWindow: 32_000,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.3,
    outputPrice: 0.9,
    deprecated: false,
    description: "Mistral's specialized coding model",
  },
  // ==========================================================================
  // Mistral Small Series (Efficient)
  // ==========================================================================
  {
    id: "mistral-small-latest",
    name: "Mistral Small",
    provider: "mistral",
    contextWindow: 32_000,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.1,
    outputPrice: 0.3,
    deprecated: false,
    description: "Mistral's cost-effective model",
  },
  // ==========================================================================
  // Pixtral (Vision)
  // ==========================================================================
  {
    id: "pixtral-large-latest",
    name: "Pixtral Large",
    provider: "mistral",
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 2.0,
    outputPrice: 6.0,
    deprecated: false,
    description: "Mistral's vision-enabled Pixtral model",
  },
];
