/**
 * OpenAI model definitions
 * @module models/providers/openai
 */

import type { ModelInfo } from "../types.js";

/**
 * OpenAI model catalog
 * Pricing: https://openai.com/api/pricing/
 * Models: https://platform.openai.com/docs/models
 */
export const OPENAI_MODELS: ModelInfo[] = [
  // ==========================================================================
  // GPT-5 Series (Latest)
  // ==========================================================================
  {
    id: "gpt-5.2",
    name: "GPT-5.2",
    provider: "openai",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 1.75,
    outputPrice: 14.0,
    cacheReadsPrice: 0.175,
    reasoningEfforts: ["none", "low", "medium", "high", "xhigh"],
    defaultReasoningEffort: "medium",
    tiers: [
      {
        name: "flex",
        contextWindow: 400_000,
        inputPrice: 0.875,
        outputPrice: 7.0,
        cacheReadsPrice: 0.0875,
      },
      {
        name: "priority",
        contextWindow: 400_000,
        inputPrice: 3.5,
        outputPrice: 28.0,
        cacheReadsPrice: 0.35,
      },
    ],
    deprecated: false,
    description: "GPT-5.2: OpenAI's flagship model for coding and agentic tasks",
  },
  {
    id: "gpt-5.1",
    name: "GPT-5.1",
    provider: "openai",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 1.25,
    outputPrice: 10.0,
    cacheReadsPrice: 0.125,
    reasoningEfforts: ["none", "low", "medium", "high"],
    defaultReasoningEffort: "medium",
    tiers: [
      {
        name: "flex",
        contextWindow: 400_000,
        inputPrice: 0.625,
        outputPrice: 5.0,
        cacheReadsPrice: 0.0625,
      },
      {
        name: "priority",
        contextWindow: 400_000,
        inputPrice: 2.5,
        outputPrice: 20.0,
        cacheReadsPrice: 0.25,
      },
    ],
    deprecated: false,
    description: "GPT-5.1: Best model for coding and agentic tasks across domains",
  },
  {
    id: "gpt-5.1-codex-max",
    name: "GPT-5.1 Codex Max",
    provider: "openai",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 1.25,
    outputPrice: 10.0,
    cacheReadsPrice: 0.125,
    reasoningEfforts: ["low", "medium", "high", "xhigh"],
    defaultReasoningEffort: "xhigh",
    tiers: [
      {
        name: "priority",
        contextWindow: 400_000,
        inputPrice: 2.5,
        outputPrice: 20.0,
        cacheReadsPrice: 0.25,
      },
    ],
    deprecated: false,
    description:
      "GPT-5.1 Codex Max: Most intelligent coding model optimized for long-horizon agentic tasks",
  },
  {
    id: "gpt-5.1-codex",
    name: "GPT-5.1 Codex",
    provider: "openai",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 1.25,
    outputPrice: 10.0,
    cacheReadsPrice: 0.125,
    reasoningEfforts: ["low", "medium", "high"],
    defaultReasoningEffort: "medium",
    tiers: [
      {
        name: "priority",
        contextWindow: 400_000,
        inputPrice: 2.5,
        outputPrice: 20.0,
        cacheReadsPrice: 0.25,
      },
    ],
    deprecated: false,
    description: "GPT-5.1 Codex: Optimized for agentic coding in Codex",
  },
  {
    id: "gpt-5.1-codex-mini",
    name: "GPT-5.1 Codex Mini",
    provider: "openai",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 0.25,
    outputPrice: 2.0,
    cacheReadsPrice: 0.025,
    reasoningEfforts: ["low", "medium", "high"],
    defaultReasoningEffort: "medium",
    deprecated: false,
    description: "GPT-5.1 Codex Mini: Cost-efficient version for agentic coding",
  },
  {
    id: "gpt-5",
    name: "GPT-5",
    provider: "openai",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 1.25,
    outputPrice: 10.0,
    cacheReadsPrice: 0.125,
    reasoningEfforts: ["minimal", "low", "medium", "high"],
    defaultReasoningEffort: "medium",
    tiers: [
      {
        name: "flex",
        contextWindow: 400_000,
        inputPrice: 0.625,
        outputPrice: 5.0,
        cacheReadsPrice: 0.0625,
      },
      {
        name: "priority",
        contextWindow: 400_000,
        inputPrice: 2.5,
        outputPrice: 20.0,
        cacheReadsPrice: 0.25,
      },
    ],
    deprecated: false,
    description: "GPT-5: Best model for coding and agentic tasks across domains",
  },
  {
    id: "gpt-5-mini",
    name: "GPT-5 Mini",
    provider: "openai",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 0.25,
    outputPrice: 2.0,
    cacheReadsPrice: 0.025,
    reasoningEfforts: ["minimal", "low", "medium", "high"],
    defaultReasoningEffort: "medium",
    tiers: [
      {
        name: "flex",
        contextWindow: 400_000,
        inputPrice: 0.125,
        outputPrice: 1.0,
        cacheReadsPrice: 0.0125,
      },
      {
        name: "priority",
        contextWindow: 400_000,
        inputPrice: 0.45,
        outputPrice: 3.6,
        cacheReadsPrice: 0.045,
      },
    ],
    deprecated: false,
    description: "GPT-5 Mini: Faster, more cost-efficient version of GPT-5",
  },
  {
    id: "gpt-5-nano",
    name: "GPT-5 Nano",
    provider: "openai",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 0.05,
    outputPrice: 0.4,
    cacheReadsPrice: 0.005,
    reasoningEfforts: ["minimal", "low", "medium", "high"],
    defaultReasoningEffort: "medium",
    tiers: [
      {
        name: "flex",
        contextWindow: 400_000,
        inputPrice: 0.025,
        outputPrice: 0.2,
        cacheReadsPrice: 0.0025,
      },
    ],
    deprecated: false,
    description: "GPT-5 Nano: Fastest, most cost-efficient version of GPT-5",
  },
  {
    id: "gpt-5-codex",
    name: "GPT-5 Codex",
    provider: "openai",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 1.25,
    outputPrice: 10.0,
    cacheReadsPrice: 0.125,
    reasoningEfforts: ["low", "medium", "high"],
    defaultReasoningEffort: "medium",
    tiers: [
      {
        name: "priority",
        contextWindow: 400_000,
        inputPrice: 2.5,
        outputPrice: 20.0,
        cacheReadsPrice: 0.25,
      },
    ],
    deprecated: false,
    description: "GPT-5 Codex: Optimized for agentic coding in Codex",
  },

  // ==========================================================================
  // O-Series (Reasoning Models)
  // ==========================================================================
  {
    id: "o3",
    name: "o3",
    provider: "openai",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: false,
    supportsPromptCache: true,
    inputPrice: 2.0,
    outputPrice: 8.0,
    cacheReadsPrice: 0.5,
    reasoningEfforts: ["low", "medium", "high"],
    defaultReasoningEffort: "medium",
    tiers: [
      {
        name: "flex",
        contextWindow: 200_000,
        inputPrice: 1.0,
        outputPrice: 4.0,
        cacheReadsPrice: 0.25,
      },
      {
        name: "priority",
        contextWindow: 200_000,
        inputPrice: 3.5,
        outputPrice: 14.0,
        cacheReadsPrice: 0.875,
      },
    ],
    deprecated: false,
    description: "o3: Advanced reasoning model with strong analytical capabilities",
  },
  {
    id: "o4-mini",
    name: "o4 Mini",
    provider: "openai",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: false,
    supportsPromptCache: true,
    inputPrice: 1.1,
    outputPrice: 4.4,
    cacheReadsPrice: 0.275,
    reasoningEfforts: ["low", "medium", "high"],
    defaultReasoningEffort: "medium",
    tiers: [
      {
        name: "flex",
        contextWindow: 200_000,
        inputPrice: 0.55,
        outputPrice: 2.2,
        cacheReadsPrice: 0.138,
      },
      {
        name: "priority",
        contextWindow: 200_000,
        inputPrice: 2.0,
        outputPrice: 8.0,
        cacheReadsPrice: 0.5,
      },
    ],
    deprecated: false,
    description: "o4 Mini: Cost-efficient reasoning model",
  },
  {
    id: "o3-mini",
    name: "o3 Mini",
    provider: "openai",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: false,
    supportsPromptCache: true,
    inputPrice: 1.1,
    outputPrice: 4.4,
    cacheReadsPrice: 0.55,
    reasoningEfforts: ["low", "medium", "high"],
    defaultReasoningEffort: "medium",
    deprecated: false,
    description: "o3 Mini: Efficient reasoning model for simpler tasks",
  },
  {
    id: "o1",
    name: "o1",
    provider: "openai",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: false,
    supportsPromptCache: true,
    inputPrice: 15.0,
    outputPrice: 60.0,
    cacheReadsPrice: 7.5,
    deprecated: false,
    description: "o1: Original reasoning model with deep analytical capabilities",
  },
  {
    id: "o1-preview",
    name: "o1 Preview",
    provider: "openai",
    contextWindow: 128_000,
    maxOutputTokens: 32_768,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: false,
    supportsPromptCache: true,
    inputPrice: 15.0,
    outputPrice: 60.0,
    cacheReadsPrice: 7.5,
    deprecated: false,
    description: "o1 Preview: Preview version of o1 reasoning model",
  },
  {
    id: "o1-mini",
    name: "o1 Mini",
    provider: "openai",
    contextWindow: 128_000,
    maxOutputTokens: 65_536,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
    supportsStreaming: false,
    supportsPromptCache: true,
    inputPrice: 1.1,
    outputPrice: 4.4,
    cacheReadsPrice: 0.55,
    deprecated: false,
    description: "o1 Mini: Smaller, faster version of o1",
  },

  // ==========================================================================
  // GPT-4 Series
  // ==========================================================================
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    provider: "openai",
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 2.0,
    outputPrice: 8.0,
    cacheReadsPrice: 0.5,
    tiers: [
      {
        name: "priority",
        contextWindow: 1_047_576,
        inputPrice: 3.5,
        outputPrice: 14.0,
        cacheReadsPrice: 0.875,
      },
    ],
    deprecated: false,
    description: "GPT-4.1: Large context model with strong general capabilities",
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    provider: "openai",
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 0.4,
    outputPrice: 1.6,
    cacheReadsPrice: 0.1,
    tiers: [
      {
        name: "priority",
        contextWindow: 1_047_576,
        inputPrice: 0.7,
        outputPrice: 2.8,
        cacheReadsPrice: 0.175,
      },
    ],
    deprecated: false,
    description: "GPT-4.1 Mini: Cost-efficient version with large context",
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    provider: "openai",
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 0.1,
    outputPrice: 0.4,
    cacheReadsPrice: 0.025,
    tiers: [
      {
        name: "priority",
        contextWindow: 1_047_576,
        inputPrice: 0.2,
        outputPrice: 0.8,
        cacheReadsPrice: 0.05,
      },
    ],
    deprecated: false,
    description: "GPT-4.1 Nano: Fastest GPT-4.1 variant",
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "openai",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 2.5,
    outputPrice: 10.0,
    cacheReadsPrice: 1.25,
    tiers: [
      {
        name: "priority",
        contextWindow: 128_000,
        inputPrice: 4.25,
        outputPrice: 17.0,
        cacheReadsPrice: 2.125,
      },
    ],
    deprecated: false,
    description: "GPT-4o: Multimodal model with vision and audio capabilities",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "openai",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: true,
    inputPrice: 0.15,
    outputPrice: 0.6,
    cacheReadsPrice: 0.075,
    tiers: [
      {
        name: "priority",
        contextWindow: 128_000,
        inputPrice: 0.25,
        outputPrice: 1.0,
        cacheReadsPrice: 0.125,
      },
    ],
    deprecated: false,
    description: "GPT-4o Mini: Cost-efficient multimodal model",
  },

  // ==========================================================================
  // Codex Series (Specialized)
  // ==========================================================================
  {
    id: "codex-mini-latest",
    name: "Codex Mini",
    provider: "openai",
    contextWindow: 200_000,
    maxOutputTokens: 16_384,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 1.5,
    outputPrice: 6.0,
    cacheReadsPrice: 0.375,
    deprecated: false,
    description:
      "Codex Mini: Cloud-based software engineering agent powered by codex-1, optimized for coding tasks",
  },

  // ==========================================================================
  // Legacy Models (Deprecated)
  // ==========================================================================
  {
    id: "gpt-4-turbo",
    name: "GPT-4 Turbo",
    provider: "openai",
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 10.0,
    outputPrice: 30.0,
    deprecated: true,
    description: "GPT-4 Turbo: Legacy model, consider upgrading to GPT-4o",
  },
  {
    id: "gpt-4",
    name: "GPT-4",
    provider: "openai",
    contextWindow: 8_192,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 30.0,
    outputPrice: 60.0,
    deprecated: true,
    description: "GPT-4: Original GPT-4 model, consider upgrading",
  },
  {
    id: "gpt-4-32k",
    name: "GPT-4 32K",
    provider: "openai",
    contextWindow: 32_000,
    maxOutputTokens: 8_192,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 60.0,
    outputPrice: 120.0,
    deprecated: true,
    description: "GPT-4 32K: Extended context GPT-4, consider upgrading",
  },
  {
    id: "gpt-3.5-turbo",
    name: "GPT-3.5 Turbo",
    provider: "openai",
    contextWindow: 16_385,
    maxOutputTokens: 4_096,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.5,
    outputPrice: 1.5,
    deprecated: true,
    description: "GPT-3.5 Turbo: Legacy model, consider upgrading",
  },
];
