/**
 * Zhipu (GLM) model definitions
 * @module models/providers/zhipu
 */

import type { ModelInfo } from "../types.js";

/**
 * Zhipu (GLM) model catalog
 * Pricing: https://open.bigmodel.cn/pricing
 * Models: https://open.bigmodel.cn/dev/api
 */
export const ZHIPU_MODELS: ModelInfo[] = [
  // ===========================================================================
  // GLM-4 Series (Legacy IDs used by tests)
  // ===========================================================================
  {
    id: "glm-4",
    name: "GLM-4",
    provider: "zhipu",
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.1,
    outputPrice: 0.1,
    deprecated: false,
    description: "Zhipu's flagship GLM-4 model",
  },
  {
    id: "glm-4-plus",
    name: "GLM-4 Plus",
    provider: "zhipu",
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: true,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.05,
    outputPrice: 0.05,
    deprecated: false,
    description: "Enhanced GLM-4 model with improved reasoning",
  },
  {
    id: "glm-4-flash",
    name: "GLM-4 Flash",
    provider: "zhipu",
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.0001,
    outputPrice: 0.0001,
    deprecated: false,
    description: "Fast, cost-effective GLM-4 model",
  },
  {
    id: "glm-4v",
    name: "GLM-4V",
    provider: "zhipu",
    contextWindow: 8_192,
    maxOutputTokens: 1_024,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.05,
    outputPrice: 0.05,
    deprecated: false,
    description: "Vision-enabled GLM-4V model",
  },
  {
    id: "glm-4v-plus",
    name: "GLM-4V Plus",
    provider: "zhipu",
    contextWindow: 8_192,
    maxOutputTokens: 1_024,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.01,
    outputPrice: 0.01,
    deprecated: false,
    description: "Improved vision model GLM-4V Plus",
  },
  // ==========================================================================
  // GLM-4.7 Series (Latest)
  // ==========================================================================
  {
    id: "glm-4.7",
    name: "GLM-4.7",
    provider: "zhipu",
    contextWindow: 200_000,
    maxOutputTokens: 98_304,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.6,
    outputPrice: 2.2,
    deprecated: false,
    description: "Zhipu's latest flagship GLM-4.7 model",
  },
  // ==========================================================================
  // GLM-4.6 Series
  // ==========================================================================
  {
    id: "glm-4.6",
    name: "GLM-4.6",
    provider: "zhipu",
    contextWindow: 200_000,
    maxOutputTokens: 32_768,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.3,
    outputPrice: 0.9,
    deprecated: false,
    description: "Zhipu's high-performance GLM-4.6 model",
  },
  {
    id: "glm-4.6v",
    name: "GLM-4.6V",
    provider: "zhipu",
    contextWindow: 131_072,
    maxOutputTokens: 16_384,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.3,
    outputPrice: 0.9,
    deprecated: false,
    description: "Zhipu's vision-enabled GLM-4.6V model",
  },
  {
    id: "glm-4.6v-flash",
    name: "GLM-4.6V Flash",
    provider: "zhipu",
    contextWindow: 131_072,
    maxOutputTokens: 16_384,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.0,
    outputPrice: 0.0,
    deprecated: false,
    description: "Zhipu's free vision model GLM-4.6V Flash",
  },
  // ==========================================================================
  // GLM-4.5 Series
  // ==========================================================================
  {
    id: "glm-4.5",
    name: "GLM-4.5",
    provider: "zhipu",
    contextWindow: 131_072,
    maxOutputTokens: 16_384,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.15,
    outputPrice: 0.45,
    deprecated: false,
    description: "Zhipu's balanced GLM-4.5 model",
  },
  {
    id: "glm-4.5-flash",
    name: "GLM-4.5 Flash",
    provider: "zhipu",
    contextWindow: 131_072,
    maxOutputTokens: 16_384,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
    supportsStreaming: true,
    supportsPromptCache: false,
    inputPrice: 0.0,
    outputPrice: 0.0,
    deprecated: false,
    description: "Zhipu's free GLM-4.5 Flash model",
  },
];
